# Generated by Django 3.0.2 on 2021-03-26 12:40

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(storage=app.models.OverwriteStorage(), upload_to='CSVFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=100)),
                ('building_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumption', models.DecimalField(decimal_places=5, max_digits=10)),
                ('reading_date_time', models.DateTimeField(default=None)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Meter')),
            ],
        ),
    ]
