# Generated by Django 3.2 on 2021-06-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
