# Generated by Django 3.2 on 2021-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_consumption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
