# Generated by Django 3.2 on 2021-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_consumption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
